/**
 * One-time clinic duplicate review list. Prints keep/drop groups and writes
 * scripts/dedupe-clinics/review-report.md. Does not change the database.
 *
 * Usage:
 *   npx tsx scripts/dedupe-clinics/classify.ts
 */

import { mkdir, writeFile } from "fs/promises";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { createDedupeClient, loadClassifiedGroups } from "./fetch-groups";
import type { ClinicCandidate, DuplicateGroup } from "./logic";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function flags(clinic: ClinicCandidate): string {
  const parts = [
    clinic.verified_klinik ? "verified" : null,
    clinic.owners > 0 ? `owners=${clinic.owners}` : null,
    clinic.premium > 0 ? `premium=${clinic.premium}` : null,
    clinic.team > 0 ? `team=${clinic.team}` : null,
    `specialties=${clinic.specialties}`,
    `events=${clinic.events}`,
  ].filter(Boolean);
  return parts.join(", ");
}

function formatClinic(clinic: ClinicCandidate, label: string): string {
  return [
    `- ${label}: ${clinic.klinikNavn}`,
    `  slug: /klinik/${clinic.klinikNavnSlug}`,
    `  city: ${clinic.lokation ?? "—"}`,
    `  address: ${clinic.adresse ?? "—"}`,
    `  flags: ${flags(clinic)}`,
    `  id: ${clinic.clinics_id}`,
  ].join("\n");
}

function formatGroup(group: DuplicateGroup, index: number): string {
  const header =
    group.decision === "always_keep"
      ? `### ${index}. ALWAYS KEEP — ${group.clinics[0]?.klinikNavn ?? "group"}`
      : `### ${index}. ${group.decision === "high_confidence" ? "KEEP" : "REVIEW"} ${group.keeper?.klinikNavn ?? "group"}`;

  const lines = [
    header,
    `- decision: ${group.decision}`,
    `- reason: ${group.reason}`,
    `- place_id: ${group.google_place_id}`,
  ];

  if (group.decision === "always_keep") {
    for (const clinic of group.clinics) {
      lines.push(formatClinic(clinic, "keep"));
    }
    return lines.join("\n");
  }

  if (group.keeper) {
    lines.push(formatClinic(group.keeper, "keep"));
  }
  for (const clinic of group.drops) {
    lines.push(formatClinic(clinic, "drop"));
  }
  return lines.join("\n");
}

function buildReport(groups: DuplicateGroup[]): string {
  const high = groups.filter((group) => group.decision === "high_confidence");
  const review = groups.filter((group) => group.decision === "needs_review");
  const keep = groups.filter((group) => group.decision === "always_keep");
  const dropCount = high.reduce((sum, group) => sum + group.drops.length, 0);

  const sections = [
    "# Clinic duplicate review",
    "",
    "Generated by `scripts/dedupe-clinics/classify.ts`. No database changes.",
    "",
    "## Summary",
    "",
    `- High confidence (proposed auto-merge): ${high.length} groups, ${dropCount} clinics to drop`,
    `- Needs review: ${review.length} groups`,
    `- Always keep: ${keep.length} groups (${keep.reduce((sum, group) => sum + group.clinics.length, 0)} clinics)`,
    "",
    "## High confidence (proposed auto-merge)",
    "",
    high.length ? high.map((group, index) => formatGroup(group, index + 1)).join("\n\n") : "_None._",
    "",
    "## Always keep",
    "",
    keep.length ? keep.map((group, index) => formatGroup(group, index + 1)).join("\n\n") : "_None._",
    "",
    "## Needs review",
    "",
    review.length ? review.map((group, index) => formatGroup(group, index + 1)).join("\n\n") : "_None._",
    "",
  ];

  return sections.join("\n");
}

async function main() {
  const supabase = createDedupeClient();
  const groups = await loadClassifiedGroups(supabase);
  const report = buildReport(groups);
  const reportPath = resolve(__dirname, "review-report.md");

  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, report, "utf8");

  console.log(report);
  console.log(`\nWrote ${reportPath}`);
  console.log("No database changes were made.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
